HOMER-487: Style the main menu dropdown
CivicActions/civicactions-homesite pull request #124
Opened 2021-06-17 13:22 UTC by iris-i

2021-06-17 13:53 UTC, jaube05 requested changes
Looks great!

2021-06-17 13:53 UTC, jaube05 commented on src/components/main-menu/_main-menu.scss
> +        background-image: url('../files/icons/menu-dropdown.svg');
Can you switch the arrows, currently showing arrow-right then click and arrow-down. Should it not be arrow-down click then arrow-up.

2021-06-17 13:53 UTC, jaube05 commented on src/components/main-menu/main-menu.js
> +        <li className='menu--list__item'><Link to='/case-studies/'>Our work</Link></li>
Maybe check with Melinda, to see if any other menu links hold child item should show a drop down?

2021-06-17 17:26 UTC, iris-i commented
Ok @jaube05, this is ready for another look. New changes:

1. The dropdown icons have been rotated.
2. Extra submenu added under "Our Work"
3. Code to close open submenus when another one is opened.
4. Moved the footer menu code into a different component.

2021-06-17 18:09 UTC, jaube05 approved these changes

2021-06-17 18:09 UTC, merged

2021-06-18 16:22 UTC, mikang commented
@iris-i @jaube05 Looks great! Thanks for the quick fix. Could you please make it so that when a user clicks anywhere outside the menu, the menu closes?

2021-06-22 22:43 UTC, iris-i commented
Sounds good @mikang, I created https://civicactions-home.atlassian.net/browse/HOMER20-538 for that.

2021-06-22 22:49 UTC, mikang commented
> Sounds good @mikang, I created https://civicactions-home.atlassian.net/browse/HOMER20-538 for that.

Thank you, @iris-i!