Homer-570/External-links-fix
CivicActions/civicactions-homesite pull request #211
Opened 2022-11-01 15:55 UTC by jaube05

Adjusting all external links to use <a> instead of the <Link> component

2022-11-02 23:35 UTC, alex9000 requested changes

2022-11-02 23:35 UTC, alex9000 commented on src/pages/services.js
> +              <a href='https://cwds.ca.gov/ ' className='external-link body-large'>
nit: extra whitespace in href attribute

2022-11-03 16:34 UTC, jaube05 commented on src/pages/careers.js
> +                <a className='external-link' href='https://medium.com/civicactions/we-hire-people-not-resumes-and-other-quirks-to-the-civicactions-application-process-7aab30d69c1c'>Learn about our un
@alex9000 I believe the rel=noopener attribute is put on when we are opening a link in a new, which is not the case here. Opening links in a new tab is not good for accessibility, unless handled with an alert error which we would need some UX.

2022-11-03 19:50 UTC, alex9000 commented on src/pages/careers.js
> +                <a className='external-link' href='https://medium.com/civicactions/we-hire-people-not-resumes-and-other-quirks-to-the-civicactions-application-process-7aab30d69c1c'>Learn about our un
I thought that recommendation applied to external links whether or not they were opened in a new window, but apparently the window.opener object is only available by navigating a link with a target attribute. I verified this by clicking the linking and seeing that window.opener was set to null on FF and Chrome. You are correct!

2022-11-03 19:58 UTC, alex9000 approved these changes

2022-11-04 13:24 UTC, merged