Adding some documentation links to the READ ME file.
CivicActions/civicactions-homesite pull request #32
Opened 2021-05-03 14:59 UTC by alexiscott

2021-05-03 15:15 UTC, iris-i commented
@alexiscott thanks for updating this!
It may be a bit confusing for new devs to still see the default gatsby readme since they won't need to run `npm init gatsby` to start this up.

Can we tweak this further and add `yarn install` instead of `npm init gatsby` ?

2021-05-03 15:15 UTC, iris-i requested changes
@alexiscott thanks for updating this!
It may be a bit confusing for new devs to still see the default gatsby readme since they won't need to run `npm init gatsby` to start this up.

Can we tweak this further and add `yarn install` instead of `npm init gatsby` ?

2021-05-04 14:43 UTC, alexiscott commented
> @alexiscott thanks for updating this!
> It may be a bit confusing for new devs to still see the default gatsby readme since they won't need to run `npm init gatsby` to start this up.
@iris-i 
Yes agreed. I dropped that section as it's legacy. Hope that works for you too!

2021-05-04 15:20 UTC, iris-i approved these changes

2021-05-04 15:20 UTC, merged