HOMER-215: React helmet tags. Initial implementation.
CivicActions/civicactions-homesite pull request #96
Opened 2021-06-09 16:06 UTC by alexiscott

2021-06-09 16:13 UTC, jaube05 requested changes
Can we add the helmet to all pages not just the homepage.

2021-06-09 17:26 UTC, jaube05 approved these changes

2021-06-09 22:29 UTC, iris-i requested changes
@alexiscott This look good but we'll need to add the description for the static pages (all files under /pages) manually. They don't get pulled from strapi.

The descriptions are written out in this airtable and are in the "Page metadata column: https://airtable.com/tblAjNqVjF7OOBRdN/viwT0wzP8FOIq0GOI?blocks=hide

Screenshot of the /contracting page title & description:
<img width="800" alt="Screen Shot 2021-06-09 at 6 28 54 PM" src="https://user-images.githubusercontent.com/5355315/121437568-8e7c2780-c950-11eb-9222-56602b44c9ee.png">

2021-06-10 11:53 UTC, alexiscott commented
@iris-i yes, thanks, I actually had been updating the titles from airtable. 
I guess I was trying to take an iterative/continuous development approach (and was going to add the description after merge) -as we are multiple developers working on the same files very often that would have helped to reduce conflicts I think.
If o.k. with you I will fix the conflicts, then can we merge it, then I will add the descriptions?

2021-06-10 12:00 UTC, iris-i approved these changes

2021-06-10 12:58 UTC, merged